[project]
name = 'clarity-game-core'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.clarity-game-core]
path = 'contracts/clarity-game-core.clar'
clarity_version = 2
epoch = 2.5

[contracts.game-core]
path = 'contracts/game-core.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
